### ISSUE TITLE
[Proposal] Release 1.0.0 and keep changelog

### ISSUE THREAD

**Issue by tomrijnbeek** [beardgame/utilities#173]
I suggest we start releasing this library on a more regular basis. As a start, I suggest we release 1.0.0 as the first canonical version of this library, and from then onward start keeping a changelog. In particular, we would use the [keepachangelog](https://keepachangelog.com/en/1.0.0/) format, which means we will have an "unreleased" section at the top of our changelog, and each PR would update the changelog with its changes.

In addition, from 1.0.0 onwards, we would also use the [Semantic Versioning](https://semver.org/spec/v2.0.0.html) guidelines for future version numbers.

**Comment by tomrijnbeek** [comment]
To clarify, I am proposing to make these changes across all Bearded libraries, including Bearded.Audio and Bearded.UI, but am using this project as a hub project.

**Comment by amulware** [comment]
I'd like clear definitions of what constitutes a breaking change and what doesn't.

**Comment by amulware** [comment]
I.e. clear specs on the versioning, before I'm happy to go ahead with that.

**Comment by tomrijnbeek** [comment]
I think the semantic versioning guidelines are detailed enough to remove
any ambiguity around versioning. The only think that may not be completely
clear is what constitutes a breaking change, but I believe there is plenty
of information in the official .NET documentation to make that
non-ambiguous.

From the Open source guidance for .NET standard libraries [1], the breaking
change definitions for corefx [2] are linked, which I believe are clear
enough that they constitute as official rules.

[1]
https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/breaking-changes
[2]
https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md

**Comment by amulware** [comment]
Those lists are very long and complicated. :D

**Comment by tomrijnbeek** [comment]
That's what you get if you ask for a definition of a breaking change, no? :P

**Comment by tomrijnbeek** [comment]
My proposal is to:

* Release 1.0.0
* From that point onward, enforce that PRs also update the changelog. [keepachangelog(https://keepachangelog.com/en/1.0.0/) suggest keeping a `CHANGELOG.md` file with an `[Unreleased]` section at the top that needs to be updated as part of each PR.
* Pre-releases can be made from `master` at any time by tagging a commit.
* Full releases constitute of a PR that bumps the version number (if relevant), moves the `[Unreleased]` section of the changelog into a named segment, and a merge into `master`, after which the `merge` commit is tagged.
  * The long term goal is that this process will be automated.

On the topic of versioning:

* The major version is increased if there is at least one breaking change recorded in the changelog.
* The minor version is increased if the major version is not increased, and there is at least one addition recorded in the changelog.
* Otherwise, the patch version is increased.
* Any change that is marked as "breaking change" in the PR template should also be marked as breaking change in the changelog.
* We will generally tolerate source breaking changes (specifically additions of classes to an existing namespace), but not binary or behaviour breaking changes.

On the topic of multiple libraries:

* My preference is that all beardkit libraries share versioning, to make it clear which versions can/should be used together.
* Combining the libraries into a single repository would be strongly beneficial if we decide to adopt shared versioning:
  * It would reduce the amount of effort to rollout a new release.
  * They would share a changelog (for better or worse, could use emoji to annotate changes made to specific library parts though). This prevents empty changelogs for new versions when a library wasn't updated between releases.

**Comment by amulware** [comment]
I agree with most of the above.

Some questions:

## Versioning, breaking changes and branching

We would have to be much more careful with breaking changes or get used to bumping major versions a lot (which feels wrong, unless there's actually a lot of big changes included?). If we're going with being more careful, can we have separate branches or tracks for different major releases so that we can keep releasing smaller updates while bunching up breaking ones into significant major releases? Obviously, we can, I guess the question is more: should we? And if so, how? Keep merging into a main develop branch and then cherry-pick all commits for new releases? Or keep separate branches for major (or even minor) releases and be really careful with where PRs go? The former strikes me as a lot simpler (less branching, PRs are easy), but it also makes making releases harder.


## Source/binary breaking changes definitions

> We will generally tolerate source breaking changes (specifically additions of classes to an existing namespace), but not binary or behaviour breaking changes.

I'm not sure I understand this entirely.
- Source breaking: with the example of adding classes/members, you're referring to introducing possible name collisions here, right?
- Aren't all source breaking changes by definition binary breaking? And you say we don't tolerate those?
- I take it we do not care at all about possible compatibility issues arising from using reflection, right?


## Multiple libraries

Let's have the discussion on sharing versions and potentially going monorepo in person. We've had some good discussion on Discord already.

**Comment by tomrijnbeek** [comment]
Conclusion after some discussion over voice:

For the time being, there doesn't seem to be intrinsic value in doing this, while it does impact our ability to iterate and experiment fast. If and when this gets more widely adopted, or we put significant in bringing this library up to standards that make it easier to reuse, we can - and will - reconsider.
