### ISSUE TITLE
Nugetify!

### ISSUE THREAD

**Issue by amulware** [beardgame/utilities#65]
Can I has package plz?

![](http://static.boredpanda.com/blog/wp-content/uploads/2014/02/funny-cats-if-it-fits-i-sits-19.jpg)

**Comment by tomrijnbeek** [comment]
Fixed in #66.

**Comment by tomrijnbeek** [comment]
Nvm

**Comment by tomrijnbeek** [comment]
Required config added in #74. Documentation on how to release added to [wiki](https://github.com/beardgame/utilities/wiki).

**Comment by amulware** [comment]
I would prefer documentation in the repo itself. Thoughts?

**Comment by tomrijnbeek** [comment]
Alright, so I thought about adding it to the repository, and ended up not doing it because of the following reasoning:

Pushing the package to NuGet is something that has to be done by package owners, i.e. your or me. That means the documentation does not apply to anybody cloning or using this library, nor would it even work for them. I feel the documentation in the repository should represent the documentation needed to work on this library as contributor. Arguably, the Wiki should represent the documentation needed to work _with_ the library, but I think I'd rather use GitHub pages for that, so we can put the documentation in the /doc folder of the repository.

I don't know what the ideal place for deployment documentation is, given that it is only really used by the two of us. Maybe we should add documentation
