### ISSUE TITLE
Move to C#7

### ISSUE THREAD

**Issue by amulware** [beardgame/utilities#84]
Unless there is a good reason not to?

Potential issues:

- Do we mind targeting .NET 4.6+?
- AppVeyor does not seem to like C#7 (but maybe that's easy to fix)

Thoughts?

**Comment by tomrijnbeek** [comment]
Moving Appveyor to Visual Studio 2017 seems to have fixed the issues we had so far, though right now we're missing ValueTuple in both Travis and Appveyor. This is probably because we are not targeting 4.6.2. Personally I would be fine targeting this. I know that it may decrease support, but .NET 4.6 is pretty easy to get (it is one of the supported redistributables on Steam for example).
